-- ==============================================================
-- DATABASE SETUP SCRIPT FOR AADHI PHOTOGRAPHY PORTFOLIO
-- ==============================================================
-- Instructions:
-- 1. Sign up/log in to Supabase (https://supabase.com).
-- 2. Create a new project.
-- 3. Go to the "SQL Editor" in the left sidebar.
-- 4. Paste this entire script and click "Run".
-- 5. Copy your Project API URL and anon Key from Settings > API.
-- ==============================================================

-- 1. Clean up existing tables if recreating
DROP TABLE IF EXISTS portfolio_data CASCADE;

-- 2. Create the portfolio settings table
CREATE TABLE IF NOT EXISTS portfolio_data (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  content jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE portfolio_data ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies

-- Allow anyone (public, anonymous, authenticated) to read the portfolio data
CREATE POLICY "Allow public read access" ON portfolio_data
  FOR SELECT
  USING (true);

-- Allow only authenticated admin users to update the portfolio data
CREATE POLICY "Allow authenticated updates" ON portfolio_data
  FOR UPDATE
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Allow only authenticated admin users to insert portfolio data (for initialization)
CREATE POLICY "Allow authenticated inserts" ON portfolio_data
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- 4. Populate initial template data
-- NOTE: In the website's Admin Panel, you can initialize or update this row.
-- The ID of the settings row must be 1.
INSERT INTO portfolio_data (id, content) VALUES (
  1,
  '{
    "logo": {
      "text": "Aadhi",
      "highlight": "Photography"
    },
    "whatsapp": "919843282808",
    "hero": {
      "badge": "25+ Years of Excellence",
      "title_em": "Moments",
      "title_before": "Capturing",
      "title_after": "That Last Forever",
      "subtitle": "Wedding & Portrait Photography · Erode, Tamil Nadu",
      "stats": [
        {"num": "25+", "label": "Years Experience"},
        {"num": "500+", "label": "Weddings Shot"},
        {"num": "1000+", "label": "Happy Clients"}
      ]
    },
    "services": [
      {
        "icon": "ti-heart",
        "title": "Wedding Photography",
        "desc": "Complete wedding coverage — mehendi, engagement, wedding ceremony, and reception. Every precious moment documented with care and artistry.",
        "price": "Starting ₹15,000 onwards"
      },
      {
        "icon": "ti-users",
        "title": "Portrait & Family",
        "desc": "Professional portraits for individuals, couples, and families. Studio and outdoor sessions available across Erode and nearby areas.",
        "price": "Starting ₹3,000 onwards"
      },
      {
        "icon": "ti-sparkles",
        "title": "Pre-wedding Shoots",
        "desc": "Cinematic pre-wedding sessions at premium locations. Relaxed, creative, and fully customised to your love story.",
        "price": "Starting ₹8,000 onwards"
      },
      {
        "icon": "ti-baby-carriage",
        "title": "Baby & Maternity",
        "desc": "Gentle, heartwarming photos of your newborn and maternity milestones. Studio setup with safe and comfortable lighting.",
        "price": "Starting ₹4,000 onwards"
      }
    ],
    "whyUs": {
      "tag": "Why Choose Us",
      "title": "Trusted by Families Across Erode",
      "items": [
        {
          "icon": "ti-camera",
          "title": "25+ Years Experience",
          "desc": "Decades of skill with thousands of moments captured across all types of events and families."
        },
        {
          "icon": "ti-clock",
          "title": "On-time Delivery",
          "desc": "Edited photos delivered within 7–10 days. No long waits, no excuses."
        },
        {
          "icon": "ti-mood-smile",
          "title": "Personal Touch",
          "desc": "Family-run studio that treats every client like our own family with full attention."
        }
      ]
    },
    "gallery": [
      {"bg": "#2a2420", "img": "", "icon": "ti-camera", "class": "tall", "category": "Wedding"},
      {"bg": "#202428", "img": "", "icon": "ti-user", "class": "", "category": "Portrait"},
      {"bg": "#1e2420", "img": "", "icon": "ti-heart", "class": "", "category": "Couple"},
      {"bg": "#252020", "img": "", "icon": "ti-users", "class": "", "category": "Family"},
      {"bg": "#20252a", "img": "", "icon": "ti-sparkles", "class": "", "category": "Pre-wedding"},
      {"bg": "#222a20", "img": "", "icon": "ti-baby-carriage", "class": "", "category": "Baby"}
    ],
    "testimonials": [
      {
        "name": "Kavitha & Arun",
        "stars": "★★★★★",
        "event": "Wedding, 2023 · Erode",
        "content": "\"Our wedding photos are absolutely stunning. Every little detail captured so beautifully — we keep looking at the album again and again.\""
      },
      {
        "name": "Priya Raman",
        "stars": "★★★★★",
        "event": "Family Portrait · Erode",
        "content": "\"Best family photoshoot experience we''ve had. Very patient with the kids, great with posing, and photos came out better than we expected!\""
      },
      {
        "name": "Deepa & Karthik",
        "stars": "★★★★★",
        "event": "Pre-wedding Shoot · Salem",
        "content": "\"Pre-wedding shoot was magical. He knows the best locations and makes you feel so comfortable in front of the camera. Highly recommend!\""
      },
      {
        "name": "Meena Suresh",
        "stars": "★★★★★",
        "event": "Baby Shoot · Erode",
        "content": "\"The newborn shoot was so gentle and beautiful. Every pose, every little moment with our baby was captured perfectly. Memories for a lifetime!\""
      }
    ],
    "contact": {
      "email": "",
      "phone": "+91 9843282808",
      "address": "Erode, Tamil Nadu",
      "location": "Based in Erode, Tamil Nadu.\nAvailable for weddings across Erode, Coimbatore, Salem, Tiruppur and nearby districts."
    }
  }'::jsonb
) ON CONFLICT DO NOTHING;
